language: php

php:
    - "5.5"
    - "5.6"
    - "7.0"
    - "hhvm"

before_script:
    - composer install --prefer-dist --dev
    - phpenv rehash

notifications:
  email: false

matrix:
  allow_failures:
    - php:
        - "5.6"
        - "hhvm"
