dist: trusty
language: php

php:
    - "5.5"
    - "5.6"
    - "7.0"
    - "7.1"
    - "hhvm"
env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"
before_script:
  - composer update $DEPENDENCIES
  - phpenv rehash

notifications:
  email: false

# matrix:
#   allow_failures:
#     - php:
#         - "5.6"
#         - "hhvm"
